/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_well_swipe_service_SwipeService */

#ifndef _Included_com_well_swipe_service_SwipeService
#define _Included_com_well_swipe_service_SwipeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_well_swipe_service_SwipeService
 * Method:    swipeDaemon
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_well_swipe_service_SwipeService_swipeDaemon
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
